### ISSUE TITLE
Add enable option

### ISSUE THREAD

**Issue by binarykitchen** [rspack-contrib/rsbuild-plugin-google-analytics#8]
That's the code I have now, and don't like it:
```ts
      plugins: [
        pluginStylus(),
        ...
        isProd() ? pluginGoogleAnalytics({ id: getGoogleTagID() }) : undefined, // <------------- This yuck
      ],
```

Creates an empty element in the plugin array. Could you add a new option `enabled`, similar like your other eslint plugin?
```ts
pluginEslint({
  enable: process.env.NODE_ENV === "production",
});
```

That would solve it elegantly. Thanks.

**Comment by chenjiahan** [comment]
How about using `&&`?

```js
      plugins: [
        isProd() && pluginGoogleAnalytics({ id: getGoogleTagID() }),
      ],
```

**Comment by binarykitchen** [comment]
Well, that's not better either, it produces `[false]` when not in production mode.

**Comment by chenjiahan** [comment]
The plugins array can accept false

**Comment by chenjiahan** [comment]
I'm open to adding an enable option and welcome PR

**Comment by binarykitchen** [comment]
I think it's important to keep all your plugins consistent. So that they all have the same pattern. Enable/Disable, depending on the environment.

(I'm a family father and for doing a PR, I'd have to examine code for which I do not have the time right now)

**Comment by binarykitchen** [comment]
Thanks!
